name: build test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xrobot-org/docker-image-webots:main
      options: --user 0

    steps:
    - uses: actions/checkout@v4
    - name: init submodule
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE" && git submodule update --init --recursive
    - name: install pip packages
      run: pip install xrobot
    - name: install linux build deps
      run: |
        apt-get update
        apt-get install -y --no-install-recommends libgpiod-dev
    - name: get modules && setup
      run: xrobot_setup
    - name: generate capturefile preset
      run: xrobot_gen_main --config User/RunConfig/capturefile.yaml --output User/xrobot_main.hpp
    - name: config cmake capturefile
      run: cmake . -Bbuild_capturefile -G Ninja
    - name: build capturefile
      run: cmake --build build_capturefile --target rm_auto_aim
    - name: generate hik preset
      run: xrobot_gen_main --config User/RunConfig/hik.yaml --output User/xrobot_main.hpp
    - name: config cmake hik
      run: cmake . -Bbuild_hik -G Ninja
    - name: build hik
      run: cmake --build build_hik --target rm_auto_aim
